name: Trigger Secondary Repo Pipeline

on:
  push:
    branches:
      - main

jobs:
  trigger_secondary_repo:
    runs-on: ubuntu-latest

    steps:
    - name: Set up things
      uses: actions/checkout@v2
    - name: run
      run: |
          ls /home/runner/work/Temp_repo_primary/Temp_repo_primary
          
      env: 
        github-token: ${{ secrets.GITHUB_TOKEN }}
