name: Trigger Secondary Repo Pipeline

on:
  pull_request:
    types: [opened]

jobs:
  trigger_secondary_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run JavaScript script
        run: node trigger_secondary.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
