name: Trigger Secondary Repo Pipeline

on:
  pull_request:
    types: [opened]

jobs:
  trigger_secondary_repo:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Secondary Repo Pipeline
      uses: actions/github-script@0.9.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { GitHub, context } = require('@actions/github');
          const token = process.env.GITHUB_TOKEN;
          const octokit = new GitHub(token);
          
          (async () => {
            try {
              const { data: pullRequest } = await octokit.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number
              });
          
              const { data: workflowRuns } = await octokit.actions.listWorkflowRuns({
                owner: farhanghaffar,
                repo: temp_repo_secondary,
                status: "queued"
              });
          
              if (workflowRuns.total_count === 0) {
                await octokit.actions.createWorkflowDispatch({
                  owner: farhanghaffar,
                  repo: temp_repo_secondary,
                  workflow_id: deploy,
                  ref: "MAIN_BRANCH",
                  inputs: {
                    pull_request_number: pullRequest.number
                  }
                });
              }
            } catch (error) {
              console.error('An error occurred: ', error);
            }
          })();
