name: Trigger Secondary Repo Pipeline

on:
  push:
    branches:
      - main

jobs:
  trigger_secondary_repo:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Upgrade pip
      run: |
        pip install pygithub
        pip --version
    - name: run python
      run: python trigger_pipeline.py
      env: 
        github-token: ${{ secrets.GITHUB_TOKEN }}
