name: Trigger Secondary Repo Pipeline

on:
  push:
    branches:
      - main

jobs:
  trigger_secondary_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
          pip install pygithub
          pip --version
          
      - name: Run Python script
        run: python trigger_pipeline.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
