name: Run JavaScript Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install @octokit/core @octokit/auth-app

      - name: Run JavaScript script
        run: |
          node trigger_secondary.js
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
