name: Trigger Secondary Repo Pipeline

on:
  pull_request:
    types: [opened]

jobs:
  trigger_secondary_repo:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Secondary Repo Pipeline
      uses: actions/github-script@0.9.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data: pullRequest } = await github.pulls.get({
            owner: context.payload.repository.owner.login,
            repo: context.payload.repository.name,
            pull_number: context.payload.pull_request.number
          });

          const octokit = github.getOctokit("${{ secrets.GITHUB_TOKEN }}");
          const { data: workflowRuns } = await octokit.actions.listWorkflowRunsForRepo({
            owner: farhanghaffar,
            repo: temp_repo_secondary,
            status: "queued"
          });

          if (workflowRuns.total_count === 0) {
            await octokit.actions.createWorkflowDispatch({
              owner: farhanghaffar,
              repo: temp_repo_secondary,
              workflow_id: deploy,
              ref: "MAIN_BRANCH",
              inputs: {
                pull_request_number: pullRequest.number
              }
            });
          }
