name: Trigger Secondary Repo Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Change directory
        run: cd NavigoPlatform  # Adjust the directory path if necessary
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Run Python script
        run: |
            python trigger_pipeline.py
        env: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
